@host = http://localhost:8000/api/v1

POST {{host}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "123",
    "email": "admin@admin.com"
}

###

POST {{host}}/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "123"
}

### CREATE PRODUCT
POST {{host}}/products
Content-Type: application/json

{
  "name": "Product 1",
  "sku": "sku12311",
  "collections": "electronics",
  "brand": "kira",
  "price": 10,
  "salePrice": 10,
  "stock": 1,
  "isFeatured": false,
  "isFreeShipping": false,
  "isVisible": true,
  "status": "ACTIVE",
  "handle": "product-1"
  }

### UPDATE PRODUCT
POST {{host}}/products/67010768603b1635a4f79daa
Content-Type: application/json

{
  "name": "Product 1",
  "sku": "sku123",
  "collections": "gadgets",
  "brand": "hp",
  "price": 10,
  "salePrice": 10,
  "stock": 1,
  "status": "ACTIVE"
  }


### GET PRODUCTS
GET {{host}}/products
Content-Type: application/json


###
GET {{host}}/collections

###
GET {{host}}/brands


###
GET {{host}}/products/66ee9bfc8e48cc9fae1bd1b0


### COLLECTIONS

### CREATE COLLECTION
POST {{host}}/collections
Content-Type: application/json

{
  "name": "Gadgets",
  "handle":  "gadgets",
  "description": "Collection Description",
  "status": "DRAFT"
}

### UPDATE COLLECTION
POST {{host}}/collections/67028e37474008c429a2dff9
Content-Type: application/json

{
  "name": "Electronics 1",
  "handle":  "electronics",
  "description": "Collection Description",
  "status": "ACTIVE"
}



### BRANDS

### CREATE BRANDS
POST {{host}}/brands
Content-Type: application/json

{
  "name": "HP",
  "handle":  "hp",
  "description": "Brand Description"
}